#!/usr/bin/bash

if ! which rmate > /dev/null; then
	echo "Installing rmate..."
	mkdir -p ~/bin/
	curl -o ~/bin/rmate https://raw.githubusercontent.com/aurora/rmate/master/rmate
	chmod +x ~/bin/rmate
	echo "Done!"
	exit
fi

echo "Rmate is already installed!"
