#!/bin/bash

# ensure sudo:
#sudo bash -c ":" || exit 1
DIR=$(git rev-parse --show-toplevel)

#application shortcuts
mkdir -p "$HOME/.local/share/applications"

find "$DIR/config/applications" -type f |
while read file; do
    ln -vsf "$file" "$HOME/.local/share/applications/$(basename "$file")"
done
