#!/bin/bash

# ensure sudo:
#sudo bash -c ":" || exit 1
DIR=$(git rev-parse --show-toplevel)

#application shortcuts
mkdir -p "$HOME/.local/share/applications"

echo Creating symlinks...

find "$DIR/config/applications" -type f | grep '\.desktop$' |
while read file; do
    [[ $(basename "$file") == _* ]] \
        || ln -vsf "$file" "$HOME/.local/share/applications/$(basename "$file")"
done
