#!/bin/bash

# ensure sudo:
sudo bash -c ":" || exit 1

DIR=$(git rev-parse --show-toplevel)

mkdir -p "$HOME/.atom"

ln -vsf "$DIR/config/dot_atom/config.cson" "$HOME/.atom/config.cson"
ln -vsf "$DIR/config/dot_atom/keymap.cson" "$HOME/.atom/keymap.cson"
