#!/bin/bash

# ensure sudo:
#sudo bash -c ":" || exit 1
DIR=$(git rev-parse --show-toplevel)

mkdir -p "$HOME/.config/lxterminal"

ln -vsf "$DIR/config/lxterminal.conf" "$HOME/.config/lxterminal/lxterminal.conf"
