#!/bin/bash

# ensure sudo:
#sudo bash -c ":" || exit 1
DIR=$(git rev-parse --show-toplevel)

mkdir -p "$HOME/.config/nixpkgs"

ln -vsf "$DIR/config/nix/config.nix" "$HOME/.config/nixpkgs/config.nix"
