#!/bin/bash

# ensure sudo:
#sudo bash -c ":" || exit 1
DIR=$(git rev-parse --show-toplevel)

mkdir -p "$HOME/.config/ptpython"

ln -vsf "$DIR/config/ptpython_config.py" "$HOME/.config/ptpython/config.py"
