#!/bin/bash

# ensure sudo:
#sudo bash -c ":" || exit 1
DIR=$(git rev-parse --show-toplevel)

mkdir -p "$HOME/Templates"

echo Creating symlinks...

find "$DIR/config/templates" -type f |
while read file; do
    ln -vsf "$file" "$HOME/Templates/$(basename "$file")"
done
