#!/bin/bash
sudo bash -c ":" || exit 1

function install {
	if ! pacman -Qi $1 > /dev/null; then
		sudo pacman --noconfirm -S $1
	fi
}
function apmget {
	package=$1
	echo $package
	if [[ ! -d "$HOME/.atom/packages/$package" ]]; then
		apm install $package
	fi
}

if ! which atom >> /dev/null; then
	read -p "Please install atom first:  (y/N)?" DO
	if [ "$DO" = "y" ]; then
		install atom
		echo
		echo
		echo "Please launch atom once before continuing... (enter)"
		read;
	else
		exit 1
	fi
fi

if ! which apm >> /dev/null; then
	echo "Atom package manager not found!"
	exit 1
fi


#user the symlink solution instead
#cp files/atom-config.cson $HOME/.atom/config.cson
#cp files/atom-keymap.cson $HOME/.atom/keymap.cson

apm disable language-python
apmget MagicPython
#apmget railscast-theme-ng # 404...
apmget railscast-theme
apmget selection-highlight
#apmget markdown-preview
apmget atom-beautify

#linter stuff
apmget linter
apmget linter-ui-default
apmget busy-signal
apmget intentions
apmget linter-clang
apmget linter-python-pep8
