#!/bin/bash
if ! which atom 2>&1 >/dev/null; then
	echo "Critical: Please install atom first!"
	exit 1
fi
if ! which apm 2>&1 >/dev/null; then
	echo "Critical: apm not found in path!"
	exit 1
fi

function apmget {
	package=$1
	echo $package
	if [[ ! -d "$HOME/.atom/packages/$package" ]]; then
		apm install $package
	fi
}

# apm list --installed --bare

# theming
#apmget railscast-theme-ng # 404...
apmget railscast-theme

# syntax definitions
apm disable language-python
apmget MagicPython
apmget atom-jinja2
apmget autocomplete-cmake
apmget language-arduino
apmget language-armasm
apmget language-autoit
apmget language-batch
apmget language-bison-flex
apmget language-cmake
apmget language-diff
apmget language-dot
apmget language-glsl
apmget language-haskell
apmget language-ini
apmget language-latex
apmget language-lua
apmget language-scala
apmget language-systemverilog
apmget language-velocity
apmget language-verilog
apmget language-vhdl
apmget language-zonefile
apmget language-docker

# pandoc
apm disable markdown-preview
apmget markdown-preview-plus
apmget graphviz-preview-plus
apmget language-markdown

# quality of life
apmget jumpy
apmget lines
apmget markdown-table-editor
apmget pigments
apmget remote-atom
apmget selection-highlight
apmget shell-it
apmget simple-align
apmget atom-beautify

# IDE
apmget atom-ide-ui
apmget busy-signal
apmget intentions

# rust
apmget ide-rust

# scala
apmget ide-scala

# C / C++
apmget atomic-rtags
#apmget ide-c-cpp # todo

# C#
#apmget ide-csharp

#linter stuff
apmget linter
apmget linter-ui-default
#apmget linter-clang
#apmget linter-python-pep8

# todo: ensure symlinked config files
