#!/bin/bash

(set -x
    sudo pacman -S --noconfirm atom
)

if ! which atom 2>&1 >/dev/null; then
	echo "Critical: Please install atom first!"
	exit 1
fi
if ! which apm 2>&1 >/dev/null; then
	echo "Critical: apm not found in path!"
	exit 1
fi

function apmget {
	package=$1
	echo $package
	if [[ ! -d "$HOME/.atom/packages/$package" ]]; then
		apm install $package
	fi
}

# apm list --installed --bare

# theming
#apmget railscast-theme-ng # 404...
apmget railscast-theme

# syntax definitions
apm disable language-python
apmget MagicPython
apmget atom-jinja2
apmget autocomplete-cmake
apmget language-arduino
apmget language-armasm
apmget language-autoit
apmget language-batch
apmget language-bison-flex
apmget language-cmake
apmget language-diff
apmget language-dg
apmget language-dot
apmget language-glsl
apmget language-haskell
apmget language-ini
apmget language-latex
apmget language-lua
apmget language-nix
apmget language-scala
apmget language-systemverilog
apmget language-velocity
apmget language-verilog
apmget language-vhdl
apmget language-zonefile
apmget language-docker
# apmget autocomplete-unity
# apmget autocomplete-cmake

# pandoc
apm disable markdown-preview
apmget markdown-preview-plus
apmget graphviz-preview-plus
apmget language-markdown
apmget zotero-citations

# quality of life
apmget fonts
#apmget jumpy
apmget lines # join lines
apmget markdown-table-editor
apmget pigments
apmget remote-atom
apmget selection-highlight
#apmget shell-it
apmget simple-align
#apmget atom-beautify
apmget copy-highlighted

# apmget live-doc-viewer # todo, test first

# IDE
apmget atom-ide-base
apmget ide-rust
#apmget ide-scala
apmget atomic-rtags # C / C++
#apmget ide-c-cpp # C / C++ todo
#apmget ide-csharp
apmget ide-python

# todo: ensure symlinked config files
