#!/usr/bin/env bash

# community

cat <<EOF | xargs pamac install --no-confirm
	git
	nmap
	dnsutils
	graphviz
	zenity
	dialog
	tldr
	jq
	yq
	entr
EOF

# AUR

cat <<EOF | xargs pamac build --no-confirm
	gron
EOF
