#!/usr/bin/env bash

# community

# https://zaiste.net/posts/shell-commands-rust/

cat <<EOF | xargs pamac install --no-confirm
	time
	htop
	unrar
	git
	nmap
	dnsutils
	graphviz
	zenity
	dialog
	tldr
	jq
	yq
	entr
	cowsay
	lolcat
	bat
	fd
	sd
	dust
	ripgrep
	git-delta
EOF

# AUR

cat <<EOF | xargs pamac build --no-confirm
	gron
	sysz
	boxes
EOF
