#!/usr/bin/bash

set -x

#git config --global core.excludesfile $HOME/.gitignore_global
git config --global core.whitespace trailing-space,space-before-tab
git config --global push.default simple
git config --global pull.rebase true
git config --global user.name "Peder Bergebakken Sundt"
git config --global user.email pbsds@hotmail.com

read -p "Have you installed your ssh credentials to github?  (y/N)?" DO
if [ "$DO" = "y" ]; then
    git config --global url.git@github.com:.insteadof https://github.com/
fi
