#!/usr/bin/bash

DIR=$(git rev-parse --show-toplevel)


# global

(set -x
    #git config --global core.excludesfile "$HOME/.gitignore_global"
    #git config --global core.whitespace "trailing-space,space-before-tab"
    #git config --global push.default "simple"
    #git config --global pull.rebase "true"
    git config --global user.name "Peder Bergebakken Sundt"
    git config --global user.email "pbsds@hotmail.com"
    #git config --global diff.algorithm "default"
    #git config --global diff.algorithm "patience"
    git config --global diff.algorithm "histogram"
    git config --global init.defaultBranch "main"
)

read -p "Have you installed your ssh credentials to github?  (y/N)?" DO
if [ "$DO" = "y" ]; then
    (set -x
        git config --global url.git@github.com:.insteadof https://github.com/
    )
fi

# pandoc to diff certain
if command -v pandoc >/dev/null; then
# https://tech.marksblogg.com/git-track-changes-in-media-office-documents.html
read -p "Setup git to use pandoc?  (y/N)?" DO
if [ "$DO" = "y" ]; then
    (set -x
        git config --global diff.to_markdown.textconv "pandoc --to markdown"
        git config --global diff.pdftotext.textconv   "sh -c 'pdftotext -layout \"$0\" -'"
        git config --global core.attributesfile       "${DIR}"/config/git_attributes_pandoc
    )
else
    (set -x
        git config --global --unset diff.to_markdown.textconv
        git config --global --unset core.attributesfile
    )
fi
fi

# git-delta diff
if command -v delta >/dev/null; then
# https://github.com/dandavison/delta#get-started
read -p "Setup git to use delta?  (y/N)?" DO
if [ "$DO" = "y" ]; then
    (set -x
        git config --global core.pager delta
        git config --global interactive.diffFilter 'delta --color-only'
        git config --global delta.navigate true
        git config --global delta.line-numbers true
        git config --global merge.conflictstyle diff3
        git config --global diff.colorMoved default
    )
else
    (set -x
        git config --global --unset core.pager
        git config --global --unset interactive.diffFilter
        git config --global --unset delta.navigate
        git config --global --unset delta.line-numbers
        git config --global --unset merge.conflictstyle
        git config --global --unset diff.colorMoved
    )
fi
fi
