#!/usr/bin/env bash

sudo bash -c ":" || exit 1
which pacman > /dev/null || exit 1

function install {
	# todo move this to seperate dependancy which all files can depend on
	# support more than arch
    if ! (pacman -Qi $1) > /dev/null; then
        echo installing $1...
        sudo pacman --noconfirm -S $1
    else
        echo omitting installing $1...
    fi
}

install pacaur

function installaur {
    if ! pacman -Qi $1 > /dev/null; then
        echo installing $1...
        #sudo pacaur --noconfirm -S $1
        VISUAL=echo pacaur --noconfirm -S $1
    else
        echo omitting installing $1...
    fi
}

function installExtension {
    url="$1"
    uuid="$(
        curl -s -L $url |
        grep data-uuid=\".*\" | sed -e "s/^.*uuid=\"//" |
        rev | cut -c2- | rev
    )"
    
    echo "installing $uuid from $url.."
    dbus-send --dest=org.gnome.Shell                       \
        --print-reply                                      \
        --type=method_call                                 \
        /org/gnome/Shell                                   \
        org.gnome.Shell.Extensions.InstallRemoteExtension  \
        string:"$uuid"
    echo
}


# TODO: automate this
read -p "Install gnome extensions?  (y/N)?" DO
if [ "$DO" = "y" ]; then

    install gnome-shell-extensions # yes, needed

    echo
    
    #essential:
    installExtension "https://extensions.gnome.org/extension/118/no-topleft-hot-corner/" # nohotcorner@azuri.free.fr
    installExtension "https://extensions.gnome.org/extension/352/middle-click-to-close-in-overview/" # middleclickclose@paolo.tranquilli.gmail.com
    installExtension "https://extensions.gnome.org/extension/949/bottompanel/" # bottompanel@tmoer93
    installExtension "https://extensions.gnome.org/extension/545/hide-top-bar/" # hidetopbar@mathieu.bidon.ca
    installExtension "https://extensions.gnome.org/extension/15/alternatetab/" # alternate-tab@gnome-shell-extensions.gcampax.github.com

    #neat
    installExtension "https://extensions.gnome.org/extension/1276/night-light-slider/"
    installExtension "https://extensions.gnome.org/extension/1191/battery-percentage/" # battery-percentage@mubaris.github.io
    installExtension "https://extensions.gnome.org/extension/1326/block-caribou/" # cariboublocker@git.keringar.xyz
    installExtension "https://extensions.gnome.org/extension/959/disable-workspace-switcher-popup/" # disable-workspace-switcher-popup@github.com
    installExtension "https://extensions.gnome.org/extension/1213/dynamic-battery/" # dynamic_battery@exalm
    installExtension "https://extensions.gnome.org/extension/744/hide-activities-button/" # Hide_Activities@shay.shayel.org
    installExtension "https://extensions.gnome.org/extension/1097/keep-awake/" # KeepAwake@jepfa.de
    installExtension "https://extensions.gnome.org/extension/708/panel-osd/" # panel-osd@berend.de.schouwer.gmail.com
    installExtension "https://extensions.gnome.org/extension/1297/remove-dash/" # Remove_Dash@localhost.localdomain
    installExtension "https://extensions.gnome.org/extension/906/sound-output-device-chooser/" # sound-output-device-chooser@kgshank.net
    installExtension "https://extensions.gnome.org/extension/1031/topicons/" # TopIcons@phocean.net
    installExtension "https://extensions.gnome.org/extension/1289/window-animations/" # window-animations@rliang.github.com

    echo
    echo
    echo "Install all plugins before continuing... (enter)"
    read

fi


install xdotool
install xclip
install adwaita-icon-theme
installaur la-capitaine-icon-theme
installaur vimix-gtk-themes-git
installaur gnome-terminal-transparency # failing?

DIR=$(git rev-parse --show-toplevel)
(
	cd "$DIR/config/dconf
	./push.sh theme.ini behaviour.ini behaviour.ini  shortcuts.ini theme.ini
)
(
	cd "$DIR/scripts/symlinks
	./opt
)
