#!/usr/bin/env bash

sudo bash -c ":" || exit 1 # ensure sudo

DIR=$(git rev-parse --show-toplevel)

sudo pacman -S --noconfirm lxterminal
( #set -x
	cd "$DIR"
	cd scripts/symlinks
	./lxterminal
	./xterminal
)


