#!/usr/bin/bash

if ! which micro > /dev/null; then
	echo "Installing micro..."
	mkdir -p ~/.local/bin
	(
		cd ~/.local/bin
		curl https://getmic.ro | bash
		chmod +x ~/.local/bin/micro
	)
	echo "Done!"
	exit
fi

echo "Micro is already installed!"
