#!/usr/bin/bash

if ! which micro > /dev/null; then
	echo "Installing micro..."
	mkdir -p ~/.local/bin
	(
		cd ~/.local/bin
		curl https://getmic.ro | bash
		chmod +x ~/.local/bin/micro
	)
	echo "Done!"
else
	echo "Micro is already installed!"
fi


echo "Installing plugins..."

micro --plugin install joinLines
micro --plugin install quoter
micro --plugin install manipulator
micro --plugin install editorconfig
