#!/usr/bin/bash

if ! which micro > /dev/null; then
	echo "Installing micro..."
	mkdir -p ~/bin
	(
		cd ~/bin
		curl https://getmic.ro | bash
		chmod +x ~/bin/micro
	)
	echo "Done!"
	exit
fi

echo "Micro is already installed!"
