#!/usr/bin/env bash

sudo bash -c ":" || {
    echo "sudo needed!";
    exit 1
}
test $(id -u) -eq "0" && {
    echo "cannot be run as root!"
    exit 2
}

sudo pacman -S --noconfirm nix direnv
sudo sed -i /etc/nix/nix.conf -e 's/^# sandbox = false$/sandbox = false/'
sudo usermod -aG nix-users $(id -un)
sudo systemctl enable --now nix-daemon

#sg nix-users 'nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs'
sg nix-users 'nix-channel --add https://nixos.org/channels/nixos-21.11 nixpkgs'
sg nix-users 'nix-channel --update nixpkgs'

