#!/usr/bin/env bash

cat <<EOF | xargs sudo pacman --noconfirm -S
	pandoc
	pandoc-crossref
	texlive-core
EOF

cat <<EOF | xargs pip install --user
	pandoc-imagine
	pandoc-codeblock-include
EOF


# TODO: hunspell for en_US en_GB and nb
