#!/usr/bin/env bash

cat <<EOF | xargs echo sudo pacman --noconfirm -S
	pandoc
	pandoc-crossref
	texlive-core
	texlive-fontsextra
	luarocks
EOF
#	texlive-latexextra

cat <<EOF | xargs echo pip install --user
	pandoc-imagine
	pandoc-codeblock-include
	mermaid-cli
EOF

# download the official lua filters:
#    https://github.com/pandoc/lua-filters
PANDOC_DIR="$HOME/.local/share/pandoc"
test -d "$PANDOC_DIR" || mkdir -p "$PANDOC_DIR"
RELEASE_URL="https://github.com/pandoc/lua-filters/releases/latest"
curl -LSs "$RELEASE_URL/download/lua-filters.tar.gz" |
    tar --strip-components=1 --one-top-level=$PANDOC_DIR -zvxf -

# TODO: hunspell for en_US en_GB and nb
