#!/usr/bin/env bash

cat <<EOF | xargs sudo pacman --noconfirm -S
	python
	python-pip
	python-wheel
	python-poetry
	python-poetry-core
EOF

(cd symlinks
    ./pudb
    ./ptpython
)


# todo:
# python-lsp-server[all]
# pyls-memestra
# pylsp-rope
# pyls-isort

