#!/usr/bin/bash

pacman -S rustup

#rustup toolchain install nightly 
#rustup default nightly

#rustup component add rls rust-analysis rust-src
#rustup component add rustfmt
#rustup component add clippy

