#!/usr/bin/bash

cat << EOF | xargs sudo pacman -S --noconfirm
    rustup
    rust-analyzer
    cargo-edit
    cargo-audit
    cargo-bloat
    cargo-depgraph
    cargo-flamegraph
    cargo-outdated
    cargo-watch
EOF

#rustup toolchain install nightly 
rustup default nightly

#rustup component add rls rust-analysis rust-src
#rustup component add rustfmt
#rustup component add clippy

